// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgajG4dWK37Uu6o9anh5Wuq3GibdkQrc',
    appId: '1:181632576401:web:04e785afff05f21c168830',
    messagingSenderId: '181632576401',
    projectId: 'ser-interior-app',
    authDomain: 'ser-interior-app.firebaseapp.com',
    storageBucket: 'ser-interior-app.firebasestorage.app',
    measurementId: 'G-RJ4RBJ4GLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV0S3hkJSnq9rxGVs9Xzk-yOWccyaiomA',
    appId: '1:181632576401:android:924d62e8aebe2fb4168830',
    messagingSenderId: '181632576401',
    projectId: 'ser-interior-app',
    storageBucket: 'ser-interior-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAurwI9N8SFi2gvP4Ti7oCsd6ocD6nnNgc',
    appId: '1:181632576401:ios:f93cd2f12ae99fe6168830',
    messagingSenderId: '181632576401',
    projectId: 'ser-interior-app',
    storageBucket: 'ser-interior-app.firebasestorage.app',
    androidClientId: '181632576401-jmfg0m2qvjj55jcn6do0jaa1jev2m0gq.apps.googleusercontent.com',
    iosClientId: '181632576401-sddmij0g5govp7gtstccf2igonka53av.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAurwI9N8SFi2gvP4Ti7oCsd6ocD6nnNgc',
    appId: '1:181632576401:ios:f93cd2f12ae99fe6168830',
    messagingSenderId: '181632576401',
    projectId: 'ser-interior-app',
    storageBucket: 'ser-interior-app.firebasestorage.app',
    androidClientId: '181632576401-jmfg0m2qvjj55jcn6do0jaa1jev2m0gq.apps.googleusercontent.com',
    iosClientId: '181632576401-sddmij0g5govp7gtstccf2igonka53av.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABgajG4dWK37Uu6o9anh5Wuq3GibdkQrc',
    appId: '1:181632576401:web:4a8788dfb9226926168830',
    messagingSenderId: '181632576401',
    projectId: 'ser-interior-app',
    authDomain: 'ser-interior-app.firebaseapp.com',
    storageBucket: 'ser-interior-app.firebasestorage.app',
    measurementId: 'G-VJD9E87WSH',
  );
}
